language: node_js
node_js:
    - "0.8"
services:
    - couchdb
env:
    global:
        - NODE_ENV=test
before_install:
    - npm install coffee-script -g
    - git clone git://github.com/mycozycloud/cozy-data-system.git
    - cd cozy-data-system 
    - npm install
    - pwd
    - start-stop-daemon --start --chdir /home/travis/build/mycozycloud/jugglingdb-cozy-adapter/cozy-data-system/ --exec /home/travis/build/mycozycloud/jugglingdb-cozy-adapter/cozy-data-system/server.coffee -b
    - ps aux | grep coffee
    - sleep 3
    - curl http://localhost:9101/
    - npm install coffee-script -g
    - cd ..
